### PR TITLE
Updated job info gathering method

### PR DESCRIPTION
**Pull request by ilayda21**
## Done
Updated job info gathering method

## QA
- Checkout the feature branch
- Install dependencies with `yarn`.
- Run `ts-node ./src/index.ts add-posts -i`
- Verify Jobs are listed correctly

Fixes https://github.com/canonical/workplace-engineering-squad/issues/416

### CODE REVIEW

**Review by goulinkh — APPROVED** [review]
LGTM

**Comment by goulinkh** [comment]
@ilayda21 Did the QA and got only one job not sure whether thats the expected result or not though, @tbille can you QA this please to make sure it works?

**Comment by ilayda21** [comment]
@goulinkh it depends on some conditions like you have to be a recruiter to see the job on your list. You can check it from "https://canonical.greenhouse.io/alljobs"

**Comment by goulinkh** [comment]
> @goulinkh it depends on some conditions like you have to be a recruiter to see the job on your list. You can check it from "https://canonical.greenhouse.io/alljobs"

In this case the results are good as I'm a recruiter on only one job :+1:

**Review by andesol — APPROVED** [review]
It works fine with my 2 jobs :+1:

**Pull request merged**
