### PR TITLE
Added regions to interactive UI

### LINKED ISSUE #30: Display regions and allow users to make multiple selections
Regions should be displayed
Users should be able to choose multiple regions.

### PR DESCRIPTION
**Pull request by ilayda21**
## Done
- Regions are displayed on the comment line.

## QA
- Checkout the feature branch
- Install dependencies with `yarn`
- Update "Job.ts" > "clonePost" method > boardPost variable :
`const boardToPost = boards.find((board) => board.name === "Test Board");`

- Run `ts-node ./src/index.ts add-job -i`
- Select one of the jobs.
- Select one of the job posts.
- Verify regions are listed.
- Press enter without selecting any region
- Verify an error is displayed and allow user to try again
- Select one or more  regions by using space
- Verify job posts are created with entered values.

- Run `ts-node ./src/index.ts delete-job -i`
- Select one of the jobs.
- Select one of the job posts.
- Verify regions are listed.
- Select one or more  regions by using space
- Verify job posts with entered values are deleted.

- Run command `ts-node ./src/index.ts add-post <job-id> -c <post-id> -r emea,apac` 
- Verify job posts are created with entered values.

- Run command `ts-node ./src/index.ts delete-posts <job-id> -s <post-id> -r emea,apac` 
- Verify job posts are deleted.

NOTE: Logs are going to be updated in another PR.

## Issue
Fixes  #30

### CODE REVIEW

**Comment by tbille** [comment]
@ilayda21 when I select a region I am getting an invalid input:

```
? What region should those job posts be? …  

▸ Invalid input
✔ americas
✔ emea
✔ apac
```

**Comment by tbille** [comment]
ah nevermind, I need to press space. We might want to add a message here

**Comment by tbille** [comment]
on the delete posts command the thank you is too early :laughing: 

image

**Comment by tbille** [comment]
delete command logs: 
```
⠇ Processing.✓ 108 job posts of Demo Job - Scenario A are deleted.
✔ Processing.
Happy hiring!
```

is that what you mean but you'll update the logs in another PR?

**Comment by ilayda21** [comment]
> delete command logs:
> 
> ```
> ⠇ Processing.✓ 108 job posts of Demo Job - Scenario A are deleted.
> ✔ Processing.
> Happy hiring!
> ```
> 
> is that what you mean but you'll update the logs in another PR?

yes exactly because i need to update them all and make them consistent

**Pull request merged**
