### PR TITLE
Display unique job post names to the user

### LINKED ISSUE #26: Display unique job posts on CLI and let user select one of them
Job posts should be retrieved.
Name of the job posts should be displayed to the user.
User should choose one of them

### PR DESCRIPTION
**Pull request by ilayda21**
## Done
- Job posts are retrieved.
- Job posts with unique names are displayed.

## QA
- Checkout the feature branch
- Install dependencies with `yarn`
- Run `ts-node ./src/index.ts add-job -i`
- Select one of the jobs.
- Verify job posts' names are displayed.
- Select one of the job posts.
- Verify job post's name and id is logged. 
- Run `ts-node ./src/index.ts delete-jobs -i`
- Select one of the jobs.
- Verify job posts' names are displayed.
- Select one of the job posts.
- Verify job post's name and id is logged.

## Issue
Fixes  #26

### CODE REVIEW

**Review by goulinkh — APPROVED** [review]
LGTM

**Comment by goulinkh** [comment]
@ilayda21 BTW `yarn dev` is an alias for `ts-node ./src/index.ts`

**Comment by goulinkh** [comment]
@ilayda21 the argument `add-job` named in the QA wasn't found as for `add-post` I got this: 
image


Should I change some code to be able to get the test board?

**Comment by ilayda21** [comment]
> @ilayda21 BTW `yarn dev` is an alias for

arguments cannot be parsed if i use yarn dev

**Comment by tbille** [comment]
@goulinkh just gave you access. It should work now

**Review by tbille — APPROVED** [review]
QA+1!!

Tested on a job that has 1 job post and another one that has 2.
It worked as expected!

**Pull request merged**
